# 应用配置文件
# 基于 AppConfig 结构生成的默认配置

# 应用基础配置
name: "Taozijun Network Technology Co., Ltd."
host: "0.0.0.0"
port: 8000
static: "static"  # 静态文件目录（例如：static 或 public）
readTimeout: "30s"
writeTimeout: "30s"
idleTimeout: "60s"
maxHeader: 10485760  # 10MB
debug: true

# CORS 跨域配置
cors:
  allowOrigins: ["*"]
  allowMethods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
  allowHeaders: ["Authorization","Content-Type"]
  exposeHeaders: []
  allowCredentials: false
  maxAge: 600  # 10 minutes

# JWT 配置
jwt:
  enableSingle: false  # 是否启用单点登录(同一个用户只能在一个设备上登录)
  expiresIn: 3600  # 1 hour
  secretKey: "2024-8x9y2z1w0v"

# 限流配置
rateLimit:
  rate: 20  # 每秒请求数限制
  burst: 40  # 突发请求数限制
  includePaths: []  # 包含限流的路径
  excludePaths: []  # 排除限流的路径

# 日志配置
logger:
  level: "info"  # 日志级别: debug, info, warn, error
  output: "both"  # 输出目标: stdout, file, both
  timeFormat: "2006-01-02T15:04:05Z07:00"  # 时间格式
  callerSkip: 3  # 调用栈跳过层数
  file:  # 文件输出配置
    path: "logs/app.log"  # 日志文件路径
    maxSizeMb: 100  # 单个日志文件最大大小(MB)
    maxBackups: 10  # 最多保留的旧日志文件数量
    maxAgeDays: 30  # 日志文件最大保留天数
    compress: true  # 是否压缩旧的日志文件
    localTime: true  # 是否使用本地时间

# 缓存配置
cache:
  driver: "redis"  # 缓存驱动: redis, memory
  
  # Redis 配置
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  prefix: ""
  
  # 连接池配置
  maxRetries: 3
  minRetryBackoff: "8ms"
  maxRetryBackoff: "512ms"
  dialTimeout: "5s"
  readTimeout: "3s"
  writeTimeout: "3s"
  poolSize: 10
  minIdleConns: 5
  maxConnAge: "1h"
  poolTimeout: "4s"
  idleTimeout: "5m"
  idleCheckFreq: "1m"
  
  # 内存缓存配置
  maxMemory: 104857600  # 100MB
  cleanupInterval: "10m"

# 数据库配置
database:
  driver: "mysql"  # 数据库驱动: mysql, postgres
  host: "localhost"
  port: 3306
  username: "root"
  password: "Aa123098.."
  database: "base"
  charset: "utf8mb4"
  timezone: "Local"
  sslMode: "disable"  # PostgreSQL SSL模式
  
  # 连接池配置
  maxOpenConns: 100
  maxIdleConns: 10
  connMaxLifetime: "1h"
  connMaxIdleTime: "10m"
  
  # GORM 配置
  logLevel: "info"  # 日志级别: silent, error, warn, info
  slowThreshold: "1s"  # 慢查询阈值
  prepareStmt: true  # 是否预编译语句
  disableForeignKeyConstraintWhenMigrating: false  # 迁移时是否禁用外键约束
